services:
  siwe-oidc:
    build: .
    ports:
      - '3000:3000'
    environment:
      - NUXT_OIDC_BASE_URL=${NUXT_OIDC_BASE_URL:-http://localhost:3000}
      - NUXT_OIDC_REDIS_URL=${NUXT_OIDC_REDIS_URL:-redis://:${REDIS_PASSWORD}@redis:6379}
      - NUXT_OIDC_RSA_PEM=${NUXT_OIDC_RSA_PEM:-}
      - NUXT_OIDC_REQUIRE_SECRET=${NUXT_OIDC_REQUIRE_SECRET:-true}
      - NUXT_OIDC_ETH_PROVIDER=${NUXT_OIDC_ETH_PROVIDER:-}
      - NUXT_OIDC_DEFAULT_CLIENTS=${NUXT_OIDC_DEFAULT_CLIENTS:-}
      - NUXT_OIDC_COOKIE_KEYS=${NUXT_OIDC_COOKIE_KEYS:-}
      - NUXT_PUBLIC_EVM_WALLET_CONNECT_PROJECT_ID=${NUXT_PUBLIC_EVM_WALLET_CONNECT_PROJECT_ID:-}
      - NUXT_PUBLIC_EVM_CHAINS_MAINNET_RPCS=${NUXT_PUBLIC_EVM_CHAINS_MAINNET_RPCS:-}
    depends_on:
      redis:
        condition: service_healthy

  redis:
    image: redis:7-alpine
    command: redis-server --requirepass ${REDIS_PASSWORD}
    healthcheck:
      test: ['CMD', 'redis-cli', '-a', '${REDIS_PASSWORD}', '--no-auth-warning', 'ping']
      interval: 5s
      timeout: 3s
      retries: 5
