services:
  siwe-oidc:
    build: .
    ports:
      - '3000:3000'
    environment:
      - NUXT_OIDC_BASE_URL=http://localhost:3000
      - NUXT_OIDC_REDIS_URL=redis://redis:6379
      - NUXT_OIDC_REQUIRE_SECRET=false
      - NUXT_PUBLIC_EVM_WALLET_CONNECT_PROJECT_ID=${NUXT_PUBLIC_EVM_WALLET_CONNECT_PROJECT_ID}
      - NUXT_PUBLIC_EVM_CHAINS_MAINNET_RPCS=${NUXT_PUBLIC_EVM_CHAINS_MAINNET_RPCS}
    depends_on:
      redis:
        condition: service_healthy

  redis:
    image: redis:7-alpine
    ports:
      - '6379:6379'
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']
      interval: 5s
      timeout: 3s
      retries: 5
